crawlersite/crawlersite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
# from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^publisher/', include('publisher.urls')),
    url(r'^publisher/(?P<publisher_id>[0-9]+)/', include('publisher.urls')),
    url(r'^publisher/(?P<publisher_id>[0-9]+)/(?P<author_id>[0-9]+)/', include('publisher.urls')),
    url(r'publisher/add/', include('publisher.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawlersite/publisher/urls.py
from django.conf.urls import url

from . import views

app_name = 'publisher'

urlpatterns = [
       # /publisher/
       url(r'^$', views.index, name='index'),

       url(r'^registration/$', views.registration, name='registration'),

       # /publisher/<publisher_id>/
       url(r'^(?P<publisher_id>[0-9]+)/$', views.detail, name='detail'),
       # /publisher/(?P<pk>[0-9]+)/<author_id>/
       url(r'^(?P<publisher_id>[0-9]+)/(?P<author_id>[0-9]+)/$', views.author_index, name='author_index'),
       # /publisher/publisher/add/
       url(r'publisher/add/$', views.create_publisher, name='create_publisher'),

       # /publisher/publisher/1
       url(r'publisher/(?P<publisher_id>[0-9]+)/$', views.update_publisher, name='update_publisher'),
       # /publisher/publisher/1/delete
       url(r'publisher/(?P<publisher_id>[0-9]+)/$', views.delete_publisher, name='delete_publisher'),

]

project_validator/urls.py
from django.contrib import admin
from django.urls import path
from crawler.views import table_view, TableListView
# from celery import task
# import threading
from crawler.static.crawler.rss_controller import Crawler

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', table_view, name='home'),
    path('', TableListView.as_view(), name='home'),
]


def start_crawler():
    crawler = Crawler()
    crawler.update_all_feeds()


start_crawler()

urls.py
from rest_framework import routers
from crawler.static.crawler.api import ArticleViewSet

router = routers.DefaultRouter()
router.register('api/Articles', ArticleViewSet,'articles')

urlpatterns = router.urls

crawlersite/publisher/models.py
from django.db import models
from django.urls import reverse


# Every time django creates a publishers, it will create a unique primary key starting from 1, then 2 and so forth
class Publisher(models.Model):
    publisher_name = models.CharField(max_length=250)
    publisher_link = models.CharField(max_length=1000)
    publisher_logo = models.FileField()
    publisher_slug = models.CharField(max_length=200, default=1)

    def get_absolute_url(self):
        return reverse('publisher:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.publisher_name + ' - ' + self.publisher_link


class Author(models.Model):
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    author_image = models.FileField()
    article_count = models.CharField(max_length=10)
    author_name = models.CharField(max_length=250)
    author_slug = models.CharField(max_length=200, default=1)

    def __str__(self):
        return self.author_name


# each article is linked to a publishers. So each foreign key will be linked to a primary key
# what cascade does, or for this in particular, whenever we delete a publishers, any thing that was linked
# to that particular publishers(primary key) will also delete the articles linked with it(foreignkeys)
class Article(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    article_title = models.CharField(max_length=250)
    article_date = models.CharField(max_length=250)

    def __str__(self):
        return self.article_title

crawlersite/publisher/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Publisher, Author


class PublisherForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ['publisher_name', 'publisher_link', 'publisher_logo', 'publisher_slug']


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ['author_name', 'author_image', 'author_slug']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

crawlersite/publisher/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from .forms import PublisherForm, UserForm
from .models import Publisher, Author, Article
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from django.urls import reverse_lazy


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# from django.http import HttpResponse
# every single view function takes the request and the request is the html request. Whenever a user
# connects to the site and requests something, like webpage, image, and stuff.


# by default, django is already setup to look at your templates directory on your apps directory,
# in this case, publisher
def index(request):
    all_publishers = Publisher.objects.all()
    return render(request, 'publisher/index.html', {'all_publishers': all_publishers})


def detail(request, publisher_id):
    publisher = get_object_or_404(Publisher, pk=publisher_id)
    return render(request, 'publisher/detail.html', {'publisher': publisher})


def author_index(request, publisher_id, author_id):
    publisher = get_object_or_404(Publisher, pk=publisher_id)
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'publisher/author_index.html', {'publisher': publisher, 'author': author})


def create_publisher(request, IMAGE_FILE_TYPES=None):
    # if not request.user.is_authenticated():
    # return render(request, 'publisher/login.html')
    # else:
    form = PublisherForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        publisher = form.save(commit=False)
        # publisher.user = request.user
        # publisher.publisher_logo = request.FILES['publisher_logo']
        # file_type = publisher.publisher_logo.url.split('.')[-1]
        # file_type = file_type.lower()
        # if file_type not in IMAGE_FILE_TYPES:
        #     context = {
        #        'publisher': publisher,
        #        'form': form,
        #        'error_message': 'Image file must be PNG, JPG, or JPEG',
        #    }
        #    return render(request, 'publisher/create_publisher.html', context)
        publisher.save()
        return render(request, 'publisher/detail.html', {'publisher': publisher})
    context = {
        "form": form,
    }
    return render(request, 'publisher/create_publisher.html', context)


def update_publisher(request):
    form = PublisherForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        publisher = form.save(commit=False)
        publisher.save()
        return render(request, 'publisher/detail.html', {'publisher': publisher})
    context = {
        "form": form,
    }
    return render(request, 'publisher/create_publisher.html', context)


def delete_publisher(request, publisher_id):
    publisher = Publisher.objects.get(pk=publisher_id)
    publisher.delete()
    publisher = Publisher.objects.filter(user=request.user)
    return render(request, 'publisher/index.html', {'publishers': publisher})


"""
def author_detail(request, publisher_id, author_id, article_id):
    publisher = get_object_or_404(Publisher, pk=publisher_id)
    author = get_object_or_404(Author, pk=author_id)
    article = get_object_or_404(article_id)
    return render(request, 'publisher/author/author_detail.html', {'article': article})
"""


def registration(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_publishers = Publisher.objects.all()
                return render(request, 'publisher/index.html', {'all_publishers': all_publishers})
    context = {
        "form": form,
    }
    return render(request, 'publisher/registration.html', context)

crawlersite/publisher/templates/publisher/author_detail.html
{% extends 'publisher/base.html' %}
{% block title %}Author Details{% endblock %}

{% block body %}

    <img src="{{ publisher.publisher_logo }}">

    <h1>{{ publisher.publisher_name }}</h1>
    <h2> {{ author.author_name }}</h2>
    <h3>Articles for {{author.author_name }}</h3>

    <ul>
        {% for article in author.article.article_set.all %}
            <li>{{ article.article_title }} - {{ article.file_type }}</li>
        {% endfor %}
    </ul>
{% endblock %}

crawlersite/publisher/templates/publisher/author_index.html
{% extends 'publisher/base.html' %}
{% block title %}Author Details{% endblock %}

{% block body %}

    <img src="{{ publisher.publisher_logo }}">

    <h1>{{ publisher.publisher_name }}</h1>
    <br>
    <img src="{{ author.author_image }}">

    <h2>Author - {{ author.author_name }}</h2>
    <h3>Articles for {{author.author_name }}</h3>

    <ul>
        {% for article in author.article_set.all %}
            <li>{{ article.article_title }} - {{ article.file_type }}</li>
        {% endfor %}
    </ul>
{% endblock %}

crawlersite/publisher/templates/publisher/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Validator{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'publisher/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{%  static 'publisher/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header stuff -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'publisher:index' %}">Validator</a>
        </div>

        <!-- Items on header-->
        <div class="collapse navbar-collapse" id="topNavBar">


            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'publisher:index' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Publishers
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'publisher:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Authors
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Articles
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'publisher:create_publisher' %}">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add Publisher
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

crawlersite/publisher/templates/publisher/create_publisher.html
{% extends 'publisher/base.html' %}
{% block title %}Add a New Publisher{% endblock %}
{% block publishers_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Publisher</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'publisher/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

crawlersite/publisher/templates/publisher/detail.html
{% extends 'publisher/base.html' %}
{% block title %}Publisher Details{% endblock %}

{% block body %}
    <img src="{{ publisher.publisher_logo.url }}">

    <h1>{{ publisher.publisher_name }}</h1>

    <ul>
         {% for author in publisher.author_set.all %}
             <li><a href="{% url 'publisher:author_index' publisher.id author.id %} ">{{ author.author_name }}</a></li>
         {% endfor %}
    </ul>
{% endblock %}

crawlersite/publisher/templates/publisher/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

crawlersite/publisher/templates/publisher/index.html
{% extends 'publisher/base.html' %}
{% block publishers_active %}active{% endblock %}

{% block title %}Publisher Details{% endblock %}

{% block body %}
<div class="publishers-container container-fluid">

    <!-- Publishers -->
    <div class="row">
        <div class="col-sm-12">
            <h3>#'s Publishers</h3>
        </div>
         {% if all_publishers %}
            {% for publisher in all_publishers %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">

                        <!----  THIS IS THE PUBLISHER LOGO STUFF ------>
                        <a href="{% url 'publisher:detail' publisher.id %}">
                            <img src="{{ publisher.publisher_logo.url }}" class="img-responsive">
                        </a>

                        <div class="caption">
                            <h2>{{ publisher.publisher_name }}</h2>

                            <!-- View Details -->
                            <a href="{% url 'publisher:detail' publisher.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete publisher -->
                            <form action="{% url 'publisher:delete_publisher' publisher.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="publisher_id" value="{{ publisher.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'publisher:create_publisher' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Publisher
                    </button>
                </a>
            </div>
        {% endif %}

    </div>
</div>
{% endblock %}

<!-- used this instead of publisher.pk --------- publisher.publisher_slug-------- learn how to slug -->

crawlersite/publisher/templates/publisher/registration.html
{% extends 'publisher/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create A New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'publisher/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}